# 配置服务端口号
server:
  port: 8080
# spring配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.48.60.226:3306/my_pro?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  servlet: #关于上传设置
    multipart:
      enabled: true #是否开启文件上传支持
      file-size-threshold: 0 #文件写入磁盘阈值
      max-file-size: 10MB #单个文件时上传的最大大小
      location: E:\\temp #文件上传临时保存位置
      max-request-size: 100MB #多个文件时上传的最大大小
      resolve-lazily: false #文件是否延迟解析

mybatis-plus:
  configuration:
    #这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      #逻辑未删除值，（逻辑删除下有效）
      logic-delete-value: 1
      #逻辑未删除值，（逻辑删除下有效）需要注入逻辑策略LogicSqlInjector，以@Bean方式注      入
      logic-not-delete-value: 0
  #别名包扫描路径，通过该属性可以给包中的类注册别名，多个package用逗号或者分号分隔
  type-aliases-package: com.tiantian.manage.entity
